requires 'perl', '5.20.3';
requires 'Mojolicious', '7';
requires 'Mojolicious::Plugin::RenderFile';
requires 'Mojo::Loader';
requires 'Mojo::Upload';
requires 'DBD::Pg';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema';
requires 'DBIx::Class::TimeStamp';
requires 'DBIx::Class::EncodedColumn';
requires 'Crypt::PBKDF2';
requires 'Email::Send::SMTP::Gmail';
requires 'Convert::Base64';
requires 'Email::Valid';